/* ****************************************************** */
/* State machine generated by Red State Machine generator */
/* Thu Apr 07 21:29:02 EEST 2016                          */
/* This file was automatically generated and will be      */
/* OVERWRITTEN if regenerated.                            */
/*  o Do not make changes to this file directly.          */
/*  o Do define your actions functions in                 */
/*     statechart_actions.c                               */
/* ****************************************************** */
#include "statechart_actions.h"

typedef enum  {
    S_GREENSTATE, /* greenState */
    S_REDSTATE, /* redState */
} state;

typedef struct inputsStruct {
    int button;  /* generic constant button setting type from input source. */
} inputs;

typedef struct outputsStruct {
    int duration;   /*  output variable duration (type taken from variable's source field - not checked) */
    int timer;   /*  output variable timer (type taken from variable's source field - not checked) */
} outputs;


void statechart_dispatch(inputs theInputSignal, outputs * out);
void preload(outputs * out);
int getState();
const inputs * getInput();
outputs * getOutput();
