//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// --------------------------------------------------------------------------------------------------
// <auto-generatedInfo>
// 	This code was generated by ResW File Code Generator (http://reswcodegen.codeplex.com)
// 	ResW File Code Generator was written by Christian Resma Helle
// 	and is under GNU General Public License version 2 (GPLv2)
// 
// 	This code contains a helper class exposing property representations
// 	of the string resources defined in the specified .ResW file
// 
// 	Generated: 01/01/2016 23:40:02
// </auto-generatedInfo>
// --------------------------------------------------------------------------------------------------
namespace BillPath.Modern.Strings
{
    using Windows.ApplicationModel.Resources;
    using Windows.UI.Core;
    
    
    public partial class ExpensesPagedView
    {
        
        private static ResourceLoader resourceLoader;
        
        static ExpensesPagedView()
        {
            string executingAssemblyName;
            executingAssemblyName = Windows.UI.Xaml.Application.Current.GetType().AssemblyQualifiedName;
            string[] executingAssemblySplit;
            executingAssemblySplit = executingAssemblyName.Split(',');
            executingAssemblyName = executingAssemblySplit[1];
            string currentAssemblyName;
            currentAssemblyName = typeof(ExpensesPagedView).AssemblyQualifiedName;
            string[] currentAssemblySplit;
            currentAssemblySplit = currentAssemblyName.Split(',');
            currentAssemblyName = currentAssemblySplit[1];
            if (CoreWindow.GetForCurrentThread() != null)
            {
                if (executingAssemblyName.Equals(currentAssemblyName))
                {
                    resourceLoader = ResourceLoader.GetForCurrentView("ExpensesPagedView");
                }
                else
                {
                    resourceLoader = ResourceLoader.GetForCurrentView(currentAssemblyName + "/ExpensesPagedView");
                }
            }
            else
            {
                if (executingAssemblyName.Equals(currentAssemblyName))
                {
                    resourceLoader = ResourceLoader.GetForViewIndependentUse("ExpensesPagedView");
                }
                else
                {
                    resourceLoader = ResourceLoader.GetForViewIndependentUse(currentAssemblyName + "/ExpensesPagedView");
                }
            }
        }
        
        /// <summary>
        /// Localized resource similar to "go to"
        /// </summary>
        public static string GoToPageButton_Content
        {
            get
            {
                return resourceLoader.GetString("GoToPageButton/Content");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Go"
        /// </summary>
        public static string GoToPageFlyoutButton_Content
        {
            get
            {
                return resourceLoader.GetString("GoToPageFlyoutButton/Content");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "next"
        /// </summary>
        public static string NextPageButton_Content
        {
            get
            {
                return resourceLoader.GetString("NextPageButton/Content");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Page {0},"
        /// </summary>
        public static string Page
        {
            get
            {
                return resourceLoader.GetString("Page");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Page:"
        /// </summary>
        public static string PageNumberTextBlock_Text
        {
            get
            {
                return resourceLoader.GetString("PageNumberTextBlock/Text");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "The total number of pages is {0}."
        /// </summary>
        public static string PagesCount
        {
            get
            {
                return resourceLoader.GetString("PagesCount");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "previous"
        /// </summary>
        public static string PreviousPageButton_Content
        {
            get
            {
                return resourceLoader.GetString("PreviousPageButton/Content");
            }
        }
    }
}
