//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// --------------------------------------------------------------------------------------------------
// <auto-generatedInfo>
// 	This code was generated by ResW File Code Generator (http://reswcodegen.codeplex.com)
// 	ResW File Code Generator was written by Christian Resma Helle
// 	and is under GNU General Public License version 2 (GPLv2)
// 
// 	This code contains a helper class exposing property representations
// 	of the string resources defined in the specified .ResW file
// 
// 	Generated: 10/10/2015 10:51:23
// </auto-generatedInfo>
// --------------------------------------------------------------------------------------------------
namespace BillPath.Modern.Strings
{
    using Windows.ApplicationModel.Resources;
    using Windows.UI.Core;
    
    
    public partial class SettingsFlyout
    {
        
        private static ResourceLoader resourceLoader;
        
        static SettingsFlyout()
        {
            string executingAssemblyName;
            executingAssemblyName = Windows.UI.Xaml.Application.Current.GetType().AssemblyQualifiedName;
            string[] executingAssemblySplit;
            executingAssemblySplit = executingAssemblyName.Split(',');
            executingAssemblyName = executingAssemblySplit[1];
            string currentAssemblyName;
            currentAssemblyName = typeof(SettingsFlyout).AssemblyQualifiedName;
            string[] currentAssemblySplit;
            currentAssemblySplit = currentAssemblyName.Split(',');
            currentAssemblyName = currentAssemblySplit[1];
            if (CoreWindow.GetForCurrentThread() != null)
            {
                if (executingAssemblyName.Equals(currentAssemblyName))
                {
                    resourceLoader = ResourceLoader.GetForCurrentView("SettingsFlyout");
                }
                else
                {
                    resourceLoader = ResourceLoader.GetForCurrentView(currentAssemblyName + "/SettingsFlyout");
                }
            }
            else
            {
                if (executingAssemblyName.Equals(currentAssemblyName))
                {
                    resourceLoader = ResourceLoader.GetForViewIndependentUse("SettingsFlyout");
                }
                else
                {
                    resourceLoader = ResourceLoader.GetForViewIndependentUse(currentAssemblyName + "/SettingsFlyout");
                }
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Currency"
        /// </summary>
        public static string Currency_Title
        {
            get
            {
                return resourceLoader.GetString("Currency/Title");
            }
        }
        
        /// <summary>
        /// Localized resource similar to "Display format"
        /// </summary>
        public static string CurrencyDisplayFormat_Text
        {
            get
            {
                return resourceLoader.GetString("CurrencyDisplayFormat/Text");
            }
        }
    }
}
