//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Andrei15193.DtoMin
{
	internal static partial class Constants
	{
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string DesignerFileExtension = "dtom";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductName = @"DtoMin";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string CompanyName = @"Andrei15193";
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Performance", "CA1823:AvoidUnusedPrivateFields")]
		public const string ProductVersion = "1.0.0.0";

		// Menu definitions
		public static readonly global::System.ComponentModel.Design.CommandID DtoMinDiagramMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DtoMinCommandSetId), 0x10000);
		public static readonly global::System.ComponentModel.Design.CommandID DtoMinExplorerMenu = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DtoMinCommandSetId), 0x10001);

		// Command definitions
		public static readonly global::System.ComponentModel.Design.CommandID ViewDtoMinExplorerCommand = new global::System.ComponentModel.Design.CommandID(new global::System.Guid(DtoMinCommandSetId), 0x0001);
	
		// Package identifier
		public const string DtoMinPackageId = "4f73bb38-772b-4042-a54f-a269413b3951";
		
		// Editor factory identifier
		public const string DtoMinEditorFactoryId = "f52bbe53-3ad0-47cc-acc9-a2c213b13e54";
		
		public const string DefaultDiagramExtension = ".diagram";
		
		// Model explorer tool window identifier
		public const string DtoMinModelExplorerToolWindowId = "25eeeb92-a8f8-4c2d-bdc7-9ec4214ce84a";
	}
}
//
// Constants not generated from values in DesignerDefinition.dsl are defined below
//
namespace Andrei15193.DtoMin
{
	internal static partial class Constants
	{
		// Menu identifier
		public const string DtoMinCommandSetId = "27c8622d-c032-49b2-8e7b-fdf461a3c515";
	}
}