//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// --------------------------------------------------------------------------------------------------
// <auto-generatedInfo>
// 	This code was generated by ResW File Code Generator (http://reswcodegen.codeplex.com)
// 	ResW File Code Generator was written by Christian Resma Helle
// 	and is under GNU General Public License version 2 (GPLv2)
// 
// 	This code contains a helper class exposing property representations
// 	of the string resources defined in the specified .ResW file
// 
// 	Generated: 09/27/2015 10:34:03
// </auto-generatedInfo>
// --------------------------------------------------------------------------------------------------
namespace BillPath.Strings
{
    using Windows.ApplicationModel.Resources;
    using Windows.UI.Core;

    public partial class ExpenseCategory
    {

        private static ResourceLoader resourceLoader;

        static ExpenseCategory()
        {
            string executingAssemblyName;
            executingAssemblyName = Windows.UI.Xaml.Application.Current.GetType().AssemblyQualifiedName;
            string[] executingAssemblySplit;
            executingAssemblySplit = executingAssemblyName.Split(',');
            executingAssemblyName = executingAssemblySplit[1];
            string currentAssemblyName;
            currentAssemblyName = typeof(ExpenseCategory).AssemblyQualifiedName;
            string[] currentAssemblySplit;
            currentAssemblySplit = currentAssemblyName.Split(',');
            currentAssemblyName = currentAssemblySplit[1];
            if (CoreWindow.GetForCurrentThread() != null)
            {
                if (executingAssemblyName.Equals(currentAssemblyName))
                {
                    resourceLoader = ResourceLoader.GetForCurrentView("ExpenseCategory");
                }
                else
                {
                    resourceLoader = ResourceLoader.GetForCurrentView(currentAssemblyName + "/ExpenseCategory");
                }
            }
            else
            {
                if (executingAssemblyName.Equals(currentAssemblyName))
                {
                    resourceLoader = ResourceLoader.GetForViewIndependentUse("ExpenseCategory");
                }
                else
                {
                    resourceLoader = ResourceLoader.GetForViewIndependentUse(currentAssemblyName + "/ExpenseCategory");
                }
            }
        }

        /// <summary>
        /// Localized resource similar to "Category name is required."
        /// </summary>
        public static string Name_Required
        {
            get
            {
                return resourceLoader.GetString("Name_Required");
            }
        }
    }
}
