//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using DslModeling = global::Microsoft.VisualStudio.Modeling;
using DslDesign = global::Microsoft.VisualStudio.Modeling.Design;
using DslDiagrams = global::Microsoft.VisualStudio.Modeling.Diagrams;
namespace Andrei15193.DtoMin
{
	/// <summary>
	/// DomainModel DtoMinDomainModel
	/// Description for Andrei15193.DtoMin.DtoMin
	/// </summary>
	[DslDesign::DisplayNameResource("Andrei15193.DtoMin.DtoMinDomainModel.DisplayName", typeof(global::Andrei15193.DtoMin.DtoMinDomainModel), "Andrei15193.DtoMin.GeneratedCode.DomainModelResx")]
	[DslDesign::DescriptionResource("Andrei15193.DtoMin.DtoMinDomainModel.Description", typeof(global::Andrei15193.DtoMin.DtoMinDomainModel), "Andrei15193.DtoMin.GeneratedCode.DomainModelResx")]
	[global::System.CLSCompliant(true)]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.CoreDomainModel))]
	[DslModeling::DependsOnDomainModel(typeof(global::Microsoft.VisualStudio.Modeling.Diagrams.CoreDesignSurfaceDomainModel))]
	[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]
	[DslModeling::DomainObjectId("e6023d52-fdf2-4b84-bcf1-fced385aa11f")]
	public partial class DtoMinDomainModel : DslModeling::DomainModel
	{
		#region Constructor, domain model Id
	
		/// <summary>
		/// DtoMinDomainModel domain model Id.
		/// </summary>
		public static readonly global::System.Guid DomainModelId = new global::System.Guid(0xe6023d52, 0xfdf2, 0x4b84, 0xbc, 0xf1, 0xfc, 0xed, 0x38, 0x5a, 0xa1, 0x1f);
	
		/// <summary>
		/// Constructor.
		/// </summary>
		/// <param name="store">Store containing the domain model.</param>
		public DtoMinDomainModel(DslModeling::Store store)
			: base(store, DomainModelId)
		{
			// Call the partial method to allow any required serialization setup to be done.
			this.InitializeSerialization(store);		
		}
		
	
		///<Summary>
		/// Defines a partial method that will be called from the constructor to
		/// allow any necessary serialization setup to be done.
		///</Summary>
		///<remarks>
		/// For a DSL created with the DSL Designer wizard, an implementation of this 
		/// method will be generated in the GeneratedCode\SerializationHelper.cs class.
		///</remarks>
		partial void InitializeSerialization(DslModeling::Store store);
	
	
		#endregion
		#region Domain model reflection
			
		/// <summary>
		/// Gets the list of generated domain model types (classes, rules, relationships).
		/// </summary>
		/// <returns>List of types.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override global::System.Type[] GetGeneratedDomainModelTypes()
		{
			return new global::System.Type[]
			{
				typeof(DTOMap),
				typeof(DTO),
				typeof(DTOAttribute),
				typeof(DTOMapHasDTOs),
				typeof(DTOHasAttributes),
				typeof(DTOReferencesDTOs),
				typeof(DtoMinDiagram),
				typeof(ExampleConnector),
				typeof(DTOCompartmentShape),
				typeof(global::Andrei15193.DtoMin.FixUpDiagram),
				typeof(global::Andrei15193.DtoMin.ConnectorRolePlayerChanged),
				typeof(global::Andrei15193.DtoMin.CompartmentItemAddRule),
				typeof(global::Andrei15193.DtoMin.CompartmentItemDeleteRule),
				typeof(global::Andrei15193.DtoMin.CompartmentItemRolePlayerChangeRule),
				typeof(global::Andrei15193.DtoMin.CompartmentItemRolePlayerPositionChangeRule),
				typeof(global::Andrei15193.DtoMin.CompartmentItemChangeRule),
			};
		}
		/// <summary>
		/// Gets the list of generated domain properties.
		/// </summary>
		/// <returns>List of property data.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		protected sealed override DomainMemberInfo[] GetGeneratedDomainProperties()
		{
			return new DomainMemberInfo[]
			{
				new DomainMemberInfo(typeof(DTOMap), "Namespace", DTOMap.NamespaceDomainPropertyId, typeof(DTOMap.NamespacePropertyHandler)),
				new DomainMemberInfo(typeof(DTO), "Name", DTO.NameDomainPropertyId, typeof(DTO.NamePropertyHandler)),
				new DomainMemberInfo(typeof(DTOAttribute), "Name", DTOAttribute.NameDomainPropertyId, typeof(DTOAttribute.NamePropertyHandler)),
				new DomainMemberInfo(typeof(DTOAttribute), "Type", DTOAttribute.TypeDomainPropertyId, typeof(DTOAttribute.TypePropertyHandler)),
				new DomainMemberInfo(typeof(DTOAttribute), "Multiplicity", DTOAttribute.MultiplicityDomainPropertyId, typeof(DTOAttribute.MultiplicityPropertyHandler)),
			};
		}
		/// <summary>
		/// Gets the list of generated domain roles.
		/// </summary>
		/// <returns>List of role data.</returns>
		protected sealed override DomainRolePlayerInfo[] GetGeneratedDomainRoles()
		{
			return new DomainRolePlayerInfo[]
			{
				new DomainRolePlayerInfo(typeof(DTOMapHasDTOs), "DTOs", DTOMapHasDTOs.DTOsDomainRoleId),
				new DomainRolePlayerInfo(typeof(DTOMapHasDTOs), "DTOMap", DTOMapHasDTOs.DTOMapDomainRoleId),
				new DomainRolePlayerInfo(typeof(DTOHasAttributes), "Attributes", DTOHasAttributes.AttributesDomainRoleId),
				new DomainRolePlayerInfo(typeof(DTOHasAttributes), "Container", DTOHasAttributes.ContainerDomainRoleId),
				new DomainRolePlayerInfo(typeof(DTOReferencesDTOs), "Childs", DTOReferencesDTOs.ChildsDomainRoleId),
				new DomainRolePlayerInfo(typeof(DTOReferencesDTOs), "Parent", DTOReferencesDTOs.ParentDomainRoleId),
			};
		}
		#endregion
		#region Factory methods
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementMap;
	
		/// <summary>
		/// Creates an element of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementType">Element type which belongs to this domain model.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1506:AvoidExcessiveClassCoupling", Justification = "Generated code.")]	
		public sealed override DslModeling::ModelElement CreateElement(DslModeling::Partition partition, global::System.Type elementType, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementType == null) throw new global::System.ArgumentNullException("elementType");
	
			if (createElementMap == null)
			{
				createElementMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(6);
				createElementMap.Add(typeof(DTOMap), 0);
				createElementMap.Add(typeof(DTO), 1);
				createElementMap.Add(typeof(DTOAttribute), 2);
				createElementMap.Add(typeof(DtoMinDiagram), 3);
				createElementMap.Add(typeof(ExampleConnector), 4);
				createElementMap.Add(typeof(DTOCompartmentShape), 5);
			}
			int index;
			if (!createElementMap.TryGetValue(elementType, out index))
			{
				// construct exception error message		
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::Andrei15193.DtoMin.DtoMinDomainModel.SingletonResourceManager.GetString("UnrecognizedElementType"),
								elementType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementType");
			}
			switch (index)
			{
				case 0: return new DTOMap(partition, propertyAssignments);
				case 1: return new DTO(partition, propertyAssignments);
				case 2: return new DTOAttribute(partition, propertyAssignments);
				case 3: return new DtoMinDiagram(partition, propertyAssignments);
				case 4: return new ExampleConnector(partition, propertyAssignments);
				case 5: return new DTOCompartmentShape(partition, propertyAssignments);
				default: return null;
			}
		}
	
		private static global::System.Collections.Generic.Dictionary<global::System.Type, int> createElementLinkMap;
	
		/// <summary>
		/// Creates an element link of specified type.
		/// </summary>
		/// <param name="partition">Partition where element is to be created.</param>
		/// <param name="elementLinkType">Element link type which belongs to this domain model.</param>
		/// <param name="roleAssignments">List of relationship role assignments for the new link.</param>
		/// <param name="propertyAssignments">New element property assignments.</param>
		/// <returns>Created element link.</returns>
		[global::System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Maintainability", "CA1502:AvoidExcessiveComplexity")]
		public sealed override DslModeling::ElementLink CreateElementLink(DslModeling::Partition partition, global::System.Type elementLinkType, DslModeling::RoleAssignment[] roleAssignments, DslModeling::PropertyAssignment[] propertyAssignments)
		{
			if (elementLinkType == null) throw new global::System.ArgumentNullException("elementLinkType");
			if (roleAssignments == null) throw new global::System.ArgumentNullException("roleAssignments");
	
			if (createElementLinkMap == null)
			{
				createElementLinkMap = new global::System.Collections.Generic.Dictionary<global::System.Type, int>(3);
				createElementLinkMap.Add(typeof(DTOMapHasDTOs), 0);
				createElementLinkMap.Add(typeof(DTOHasAttributes), 1);
				createElementLinkMap.Add(typeof(DTOReferencesDTOs), 2);
			}
			int index;
			if (!createElementLinkMap.TryGetValue(elementLinkType, out index))
			{
				// construct exception error message
				string exceptionError = string.Format(
								global::System.Globalization.CultureInfo.CurrentCulture,
								global::Andrei15193.DtoMin.DtoMinDomainModel.SingletonResourceManager.GetString("UnrecognizedElementLinkType"),
								elementLinkType.Name);
				throw new global::System.ArgumentException(exceptionError, "elementLinkType");
			
			}
			switch (index)
			{
				case 0: return new DTOMapHasDTOs(partition, roleAssignments, propertyAssignments);
				case 1: return new DTOHasAttributes(partition, roleAssignments, propertyAssignments);
				case 2: return new DTOReferencesDTOs(partition, roleAssignments, propertyAssignments);
				default: return null;
			}
		}
		#endregion
		#region Resource manager
		
		private static global::System.Resources.ResourceManager resourceManager;
		
		/// <summary>
		/// The base name of this model's resources.
		/// </summary>
		public const string ResourceBaseName = "Andrei15193.DtoMin.GeneratedCode.DomainModelResx";
		
		/// <summary>
		/// Gets the DomainModel's ResourceManager. If the ResourceManager does not already exist, then it is created.
		/// </summary>
		public override global::System.Resources.ResourceManager ResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				return DtoMinDomainModel.SingletonResourceManager;
			}
		}
	
		/// <summary>
		/// Gets the Singleton ResourceManager for this domain model.
		/// </summary>
		public static global::System.Resources.ResourceManager SingletonResourceManager
		{
			[global::System.Diagnostics.DebuggerStepThrough]
			get
			{
				if (DtoMinDomainModel.resourceManager == null)
				{
					DtoMinDomainModel.resourceManager = new global::System.Resources.ResourceManager(ResourceBaseName, typeof(DtoMinDomainModel).Assembly);
				}
				return DtoMinDomainModel.resourceManager;
			}
		}
		#endregion
		#region Copy/Remove closures
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter copyClosure;
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter removeClosure;
		/// <summary>
		/// Returns an IElementVisitorFilter that corresponds to the ClosureType.
		/// </summary>
		/// <param name="type">closure type</param>
		/// <param name="rootElements">collection of root elements</param>
		/// <returns>IElementVisitorFilter or null</returns>
		public override DslModeling::IElementVisitorFilter GetClosureFilter(DslModeling::ClosureType type, global::System.Collections.Generic.ICollection<DslModeling::ModelElement> rootElements)
		{
			switch (type)
			{
				case DslModeling::ClosureType.CopyClosure:
					return DtoMinDomainModel.CopyClosure;
				case DslModeling::ClosureType.DeleteClosure:
					return DtoMinDomainModel.DeleteClosure;
			}
			return base.GetClosureFilter(type, rootElements);
		}
		/// <summary>
		/// CopyClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter CopyClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (DtoMinDomainModel.copyClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter copyFilter = new DslModeling::ChainingElementVisitorFilter();
					copyFilter.AddFilter(new DtoMinCopyClosure());
					copyFilter.AddFilter(new DslModeling::CoreCopyClosure());
					copyFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceCopyClosure());
					
					DtoMinDomainModel.copyClosure = copyFilter;
				}
				return DtoMinDomainModel.copyClosure;
			}
		}
		/// <summary>
		/// DeleteClosure cache
		/// </summary>
		private static DslModeling::IElementVisitorFilter DeleteClosure
		{
			get
			{
				// Incorporate all of the closures from the models we extend
				if (DtoMinDomainModel.removeClosure == null)
				{
					DslModeling::ChainingElementVisitorFilter removeFilter = new DslModeling::ChainingElementVisitorFilter();
					removeFilter.AddFilter(new DtoMinDeleteClosure());
					removeFilter.AddFilter(new DslModeling::CoreDeleteClosure());
					removeFilter.AddFilter(new DslDiagrams::CoreDesignSurfaceDeleteClosure());
		
					DtoMinDomainModel.removeClosure = removeFilter;
				}
				return DtoMinDomainModel.removeClosure;
			}
		}
		#endregion
		#region Diagram rule helpers
		/// <summary>
		/// Enables rules in this domain model related to diagram fixup for the given store.
		/// If diagram data will be loaded into the store, this method should be called first to ensure
		/// that the diagram behaves properly.
		/// </summary>
		public static void EnableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.EnableRule(typeof(global::Andrei15193.DtoMin.FixUpDiagram));
			ruleManager.EnableRule(typeof(global::Andrei15193.DtoMin.ConnectorRolePlayerChanged));
			ruleManager.EnableRule(typeof(global::Andrei15193.DtoMin.CompartmentItemAddRule));
			ruleManager.EnableRule(typeof(global::Andrei15193.DtoMin.CompartmentItemDeleteRule));
			ruleManager.EnableRule(typeof(global::Andrei15193.DtoMin.CompartmentItemRolePlayerChangeRule));
			ruleManager.EnableRule(typeof(global::Andrei15193.DtoMin.CompartmentItemRolePlayerPositionChangeRule));
			ruleManager.EnableRule(typeof(global::Andrei15193.DtoMin.CompartmentItemChangeRule));
		}
		
		/// <summary>
		/// Disables rules in this domain model related to diagram fixup for the given store.
		/// </summary>
		public static void DisableDiagramRules(DslModeling::Store store)
		{
			if(store == null) throw new global::System.ArgumentNullException("store");
			
			DslModeling::RuleManager ruleManager = store.RuleManager;
			ruleManager.DisableRule(typeof(global::Andrei15193.DtoMin.FixUpDiagram));
			ruleManager.DisableRule(typeof(global::Andrei15193.DtoMin.ConnectorRolePlayerChanged));
			ruleManager.DisableRule(typeof(global::Andrei15193.DtoMin.CompartmentItemAddRule));
			ruleManager.DisableRule(typeof(global::Andrei15193.DtoMin.CompartmentItemDeleteRule));
			ruleManager.DisableRule(typeof(global::Andrei15193.DtoMin.CompartmentItemRolePlayerChangeRule));
			ruleManager.DisableRule(typeof(global::Andrei15193.DtoMin.CompartmentItemRolePlayerPositionChangeRule));
			ruleManager.DisableRule(typeof(global::Andrei15193.DtoMin.CompartmentItemChangeRule));
		}
		#endregion
	}
		
	#region Copy/Remove closure classes
	/// <summary>
	/// Remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class DtoMinDeleteClosure : DtoMinDeleteClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public DtoMinDeleteClosure() : base()
		{
		}
	}
	
	/// <summary>
	/// Base class for remove closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class DtoMinDeleteClosureBase : DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary domainRoles;
		/// <summary>
		/// Constructor
		/// </summary>
		public DtoMinDeleteClosureBase()
		{
			#region Initialize DomainData Table
			DomainRoles.Add(global::Andrei15193.DtoMin.DTOMapHasDTOs.DTOMapDomainRoleId, true);
			DomainRoles.Add(global::Andrei15193.DtoMin.DTOHasAttributes.ContainerDomainRoleId, true);
			#endregion
		}
		/// <summary>
		/// Called to ask the filter if a particular relationship from a source element should be included in the traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="sourceRoleInfo">DomainRoleInfo of the role that the source element is playing in the relationship</param>
		/// <param name="domainRelationshipInfo">DomainRelationshipInfo for the ElementLink in question</param>
		/// <param name="targetRelationship">Relationship in question</param>
		/// <returns>Yes if the relationship should be traversed</returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRelationship(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::DomainRoleInfo sourceRoleInfo, DslModeling::DomainRelationshipInfo domainRelationshipInfo, DslModeling::ElementLink targetRelationship)
		{
			return DslModeling::VisitorFilterResult.Yes;
		}
		/// <summary>
		/// Called to ask the filter if a particular role player should be Visited during traversal
		/// </summary>
		/// <param name="walker">ElementWalker that is traversing the model</param>
		/// <param name="sourceElement">Model Element playing the source role</param>
		/// <param name="elementLink">Element Link that forms the relationship to the role player in question</param>
		/// <param name="targetDomainRole">DomainRoleInfo of the target role</param>
		/// <param name="targetRolePlayer">Model Element that plays the target role in the relationship</param>
		/// <returns></returns>
		public virtual DslModeling::VisitorFilterResult ShouldVisitRolePlayer(DslModeling::ElementWalker walker, DslModeling::ModelElement sourceElement, DslModeling::ElementLink elementLink, DslModeling::DomainRoleInfo targetDomainRole, DslModeling::ModelElement targetRolePlayer)
		{
			if (targetDomainRole == null) throw new global::System.ArgumentNullException("targetDomainRole");
			return this.DomainRoles.Contains(targetDomainRole.Id) ? DslModeling::VisitorFilterResult.Yes : DslModeling::VisitorFilterResult.DoNotCare;
		}
		/// <summary>
		/// DomainRoles
		/// </summary>
		private global::System.Collections.Specialized.HybridDictionary DomainRoles
		{
			get
			{
				if (this.domainRoles == null)
				{
					this.domainRoles = new global::System.Collections.Specialized.HybridDictionary();
				}
				return this.domainRoles;
			}
		}
	
	}
	/// <summary>
	/// Copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class DtoMinCopyClosure : DtoMinCopyClosureBase, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public DtoMinCopyClosure() : base()
		{
		}
	}
	/// <summary>
	/// Base class for copy closure visitor filter
	/// </summary>
	[global::System.CLSCompliant(true)]
	public partial class DtoMinCopyClosureBase : DslModeling::CopyClosureFilter, DslModeling::IElementVisitorFilter
	{
		/// <summary>
		/// Constructor
		/// </summary>
		public DtoMinCopyClosureBase():base()
		{
		}
	}
	#endregion
		
}
namespace Andrei15193.DtoMin
{
	/// <summary>
	/// DomainEnumeration: AttributeType
	/// Description for Andrei15193.DtoMin.AttributeType
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum AttributeType
	{
		/// <summary>
		/// Int
		/// Represents a 32-bit integer
		/// </summary>
		[DslDesign::DescriptionResource("Andrei15193.DtoMin.AttributeType/Int.Description", typeof(global::Andrei15193.DtoMin.DtoMinDomainModel), "Andrei15193.DtoMin.GeneratedCode.DomainModelResx")]
		Int = 1,
		/// <summary>
		/// Text
		/// Represent a list of characters
		/// </summary>
		[DslDesign::DescriptionResource("Andrei15193.DtoMin.AttributeType/Text.Description", typeof(global::Andrei15193.DtoMin.DtoMinDomainModel), "Andrei15193.DtoMin.GeneratedCode.DomainModelResx")]
		Text = 0,
		/// <summary>
		/// Float
		/// Represents a 64-bit floating point number
		/// </summary>
		[DslDesign::DescriptionResource("Andrei15193.DtoMin.AttributeType/Float.Description", typeof(global::Andrei15193.DtoMin.DtoMinDomainModel), "Andrei15193.DtoMin.GeneratedCode.DomainModelResx")]
		Float = 2,
		/// <summary>
		/// DateTime
		/// Represents a date and a time span
		/// </summary>
		[DslDesign::DescriptionResource("Andrei15193.DtoMin.AttributeType/DateTime.Description", typeof(global::Andrei15193.DtoMin.DtoMinDomainModel), "Andrei15193.DtoMin.GeneratedCode.DomainModelResx")]
		DateTime = 4,
	}
}
namespace Andrei15193.DtoMin
{
	/// <summary>
	/// DomainEnumeration: Multiplicity
	/// Description for Andrei15193.DtoMin.Multiplicity
	/// </summary>
	[global::System.CLSCompliant(true)]
	public enum Multiplicity
	{
		/// <summary>
		/// Single
		/// Description for Andrei15193.DtoMin.Multiplicity.Single
		/// </summary>
		[DslDesign::DescriptionResource("Andrei15193.DtoMin.Multiplicity/Single.Description", typeof(global::Andrei15193.DtoMin.DtoMinDomainModel), "Andrei15193.DtoMin.GeneratedCode.DomainModelResx")]
		Single = 0,
		/// <summary>
		/// Collection
		/// Description for Andrei15193.DtoMin.Multiplicity.Collection
		/// </summary>
		[DslDesign::DescriptionResource("Andrei15193.DtoMin.Multiplicity/Collection.Description", typeof(global::Andrei15193.DtoMin.DtoMinDomainModel), "Andrei15193.DtoMin.GeneratedCode.DomainModelResx")]
		Collection = 1,
	}
}

