/* ****************************************************** */
/* State machine generated by Red State Machine generator */
/* Thu Apr 07 21:29:02 EEST 2016                          */
/* This file was automatically generated and will be      */
/* OVERWRITTEN if regenerated.                            */
/*  o Do not make changes to this file directly.          */
/*  o Do define your actions functions in                 */
/*     statechart_actions.c                               */
/* ****************************************************** */
void greenOff(); /* Action: greenOff */
void greenOn(); /* Action: greenOn */
void incrementDuration(); /* Action: incrementDuration */
void redOff(); /* Action: redOff */
void redOn(); /* Action: redOn */
